# Generated by Django 4.0.2 on 2023-11-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('milege', models.DecimalField(blank=True, decimal_places=2, max_digits=1000)),
                ('passanger_seats', models.IntegerField(default=4)),
                ('image', models.ImageField(blank=True, upload_to='cars/')),
                ('imgae_url', models.CharField(blank=True, max_length=50000)),
                ('car_number', models.CharField(blank=True, max_length=50)),
                ('review', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.IntegerField(blank=True)),
                ('kms', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('image_url', models.CharField(blank=True, max_length=50000)),
                ('pickup_stop', models.CharField(blank=True, max_length=50000)),
                ('drop_stop', models.CharField(blank=True, max_length=50000)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_user', to=settings.AUTH_USER_MODEL)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_end_point', to='cabs.city')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_start_point', to='cabs.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripTimeTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_trip', to='cabs.cars')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trip', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_table', to='cabs.trips')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('trip_status', models.CharField(choices=[('completed', 'completed'), ('started', 'started'), ('scheduled', 'scheduled'), ('cancelled', 'cancelled')], default='scheduled', max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_status', to='cabs.triptimetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('business_status', models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], default='profit', max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_status', to='cabs.triptimetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='car_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='car_images', to='cabs.File'),
        ),
        migrations.AddField(
            model_name='cars',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_no', models.IntegerField(default=1)),
                ('seats', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='waiting', max_length=100)),
                ('payment_status', models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], default='unpaid', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokking_trip', to='cabs.triptimetable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
