# Generated by Django 4.0.2 on 2023-08-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='milege',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000),
        ),
    ]
