# Generated by Django 4.0.2 on 2023-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='review2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
