# Generated by Django 4.0.2 on 2023-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0004_city_alter_cars_driver_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='trip_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
