# Generated by Django 4.0.2 on 2023-08-26 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0007_booking_seats_booking_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTimeTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_table', to='cabs.trips')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('trip_status', models.CharField(choices=[('completed', 'completed'), ('started', 'started'), ('scheduled', 'scheduled'), ('cancelled', 'cancelled')], default='scheduled', max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_status', to='cabs.triptimetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokking_trip', to='cabs.triptimetable'),
        ),
    ]
