# Generated by Django 4.0.2 on 2023-08-26 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0008_triptimetable_tripstatus_alter_booking_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='passanger_seats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='trips',
            name='kms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('business_status', models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], default='profit', max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_status', to='cabs.triptimetable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
