# Generated by Django 4.0.2 on 2023-09-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0009_cars_passanger_seats_trips_kms_profitloss'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars/'),
        ),
    ]
