# Generated by Django 4.0.2 on 2023-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0010_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_no',
            field=models.IntegerField(),
        ),
    ]
