# Generated by Django 4.0.2 on 2023-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0011_alter_booking_booking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_no',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
