# Generated by Django 4.0.2 on 2023-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0014_alter_booking_booking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
