# Generated by Django 4.0.2 on 2023-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0015_trips_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='image_url',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
