# Generated by Django 4.0.2 on 2023-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0016_alter_trips_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='imgae_url',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
