# Generated by Django 4.0.2 on 2023-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0017_cars_imgae_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trips',
            name='drop_stop',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AddField(
            model_name='trips',
            name='pickup_stop',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='waiting', max_length=100),
        ),
    ]
