# Generated by Django 4.0.2 on 2023-09-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabs', '0018_cars_car_number_trips_drop_stop_trips_pickup_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptimetable',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_trip', to='cabs.cars'),
        ),
        migrations.AddField(
            model_name='triptimetable',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trip', to=settings.AUTH_USER_MODEL),
        ),
    ]
