# Generated by Django 4.0.2 on 2023-10-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabs', '0019_triptimetable_car_triptimetable_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='car_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='car_images', to='cabs.File'),
        ),
    ]
