# Generated by Django 4.0.2 on 2023-08-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('driver', 'driver')], max_length=20),
        ),
    ]
